### ISSUE TITLE
Error instalando modulo

### ISSUE THREAD

**Issue by nehuen871** [tryton-ar/account_ar#16]
buenas!, me esta tirando es error al tratar de instalar el modulo.
Ayuda!

28309 139921063790336 [2020-02-04 16:38:58,640] ERROR trytond.convert Error while parsing xml file:
In tag record model account.account.type.template with id account_ar.account_type_activo.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trytond/convert.py", line 456, in parse_xmlstream
    self.sax_parser.parse(source)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 473, in EndElement
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "/usr/local/lib/python3.6/dist-packages/trytond/convert.py", line 515, in endElement
    self.taghandler = self.taghandler.endElement(name)
  File "/usr/local/lib/python3.6/dist-packages/trytond/convert.py", line 295, in endElement
    self.model.__name__, self.values, self.xml_id)
  File "/usr/local/lib/python3.6/dist-packages/trytond/convert.py", line 691, in import_record
    self.create_records(model, [values], [fs_id])
  File "/usr/local/lib/python3.6/dist-packages/trytond/convert.py", line 697, in create_records
    records = Model.create(vlist)
  File "/usr/local/lib/python3.6/dist-packages/trytond/model/modelsql.py", line 159, in wrapper
    return func(cls, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trytond/model/modelsql.py", line 677, in create
    cls._validate(sub_records)
  File "/usr/local/lib/python3.6/dist-packages/trytond/model/modelstorage.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trytond/model/modelstorage.py", line 1204, in _validate
    field_name, field)
  File "/usr/local/lib/python3.6/dist-packages/trytond/model/modelstorage.py", line 1193, in required_test
    **cls.__names__(field_name)))
trytond.model.modelstorage.RequiredValidationError: A value is required for field "Statement" in "Account Type Template". -

**Comment by lukio** [comment]
Hola @nehuen871 Nos podrás indicar en que versión de tryton estas queriendo instalar el módulo?

La versión actualmente esta desarrollada/testeada hasta la versión 5.0 inclusive.

**Comment by nehuen871** [comment]
5.4.4

**Comment by lukio** [comment]
Hola, esto se debe a unos cambios que se hicieron desde la [versión 5.2 ](https://discuss.tryton.org/t/tryton-release-5-2/1294)

> To simplify the account creation, we merged the two concepts of type and kind. Now everything is defined on the type. This is simpler for the user because now an account only requires a name, a parent and a type (inherited by default from the parent). Also new, a type can have multiple usage like revenue and expense etc.

Dicho esto, hay que modificar el xml que define las cuentas.

@nehuen871 nuevamente te comento que los módulos de la localización han sido desarrollados y testeados hasta la versión 5.0 ya que es la versión LTS (Long Time Support). Si no es requerido utilizar la versión 5.4, entonces te recomienda que implementes la 5.0 ya que desconozco cuando se realizará la actualización a versiones superiores.

**Comment by nehuen871** [comment]
ah ok, podrías pasarme de donde bajarme el versión 5.0 por que con el gestor de descargas me dice que no esta la versión 5.0

**Comment by x3m0** [comment]
Saludos,

Soy nuevo en esto y les pido que me ayuden a mostrarme como instalo tryton argentina en mi sistema operativo unbutu 2.1 tengo una raspberry pi4 8 Gb
